print("Nama:Raka Muhammad Rabbani")
print("NIM :0110223050")
print("Kelas:TI01")
print("Alamat:Gunung Putri Bogor")
print()
print("Nama:Muhammad Fahmi Romadhon")
print("NIM :0110223049")
print("Kelas:TI01")
print("Alamat:Gunung Putri Bogor")
print()
print("Penjumlahan dua bilangan")
print(5+2)
print()
print("Pengurangan dua bilangan")
print(5-2)
print()
print("Perkalian dua bilangan")
print(5*2)
print()
print("Pembagian dua bilangan")
print(5/2)